#!/bin/bash -l 


source /home/junb/miniconda3/bin/activate
conda activate masam

cd /mnt/scratch/junb/TractSegVis/TractSeg

DATA_PATH="/mnt/scratch/junb/TractSegVis/"

# training
CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 0 --data_path $DATA_PATH --config CamCan_Ping_experiment_swinunetr --en CamCan_Ping_experiment_swinunetr --train True --test True --seg --num_processes 4 --gradient_clip 1 & #--rt --with_id TRAC-1125 &
sleep 40
CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 1 --data_path $DATA_PATH --config CamCan_Ping_experiment_swinunetr --en CamCan_Ping_experiment_swinunetr --train True --test True --seg --num_processes 4 --gradient_clip 1 & #--rt --with_id TRAC-1126 &
sleep 40
CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 2 --data_path $DATA_PATH --config CamCan_Ping_experiment_swinunetr --en CamCan_Ping_experiment_swinunetr --train True --test True --seg --num_processes 4 --gradient_clip 1 & #--rt --with_id TRAC-1127 &
wait

# inference only
#./ExpRunner --fold 0 --data_path /grand/NeuroX/junbeom/TractSegVis --config Ping_experiment_TractSeg --en Ping_experiment_TractSeg --train False --test True --lw --weights_path /grand/NeuroX/junbeom/TractSegVis/TractSeg/CamCan_exp/wholeCamCan_experiment_TractSeg_x14/best_weights_ep73.npz #--seg 
#./ExpRunner --config wholevisualtract_experiment --en run_with_vis_settings --train True --test True
