#!/bin/bash -l 


source /home/junb/miniconda3/bin/activate
conda activate masam

cd /mnt/scratch/junb/TractSegVis/TractSeg

DATA_PATH="/mnt/scratch/junb/TractSegVis/"



# training
CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 0 --data_path $DATA_PATH --config CamCan_Ping_experiment_TractSeg --en CamCan_Ping_experiment_TractSeg --train True --test True --seg --num_processes 4 & # TRAC-1147 &
sleep 40
CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 1 --data_path $DATA_PATH --config CamCan_Ping_experiment_TractSeg --en CamCan_Ping_experiment_TractSeg --train True --test True --seg --num_processes 4 & #--rt --with_id TRAC-1150 &
sleep 40
CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 2 --data_path $DATA_PATH --config CamCan_Ping_experiment_TractSeg --en CamCan_Ping_experiment_TractSeg --train True --test True --seg --num_processes 4 & #--rt --with_id TRAC-1154 &
wait

