#!/usr/bin/env python

"""
This module is for training the model. See Readme.md for more details about training your own model.

Examples:
    Run local:
    $ ExpRunner --config=XXX

    Predicting with new config setup:
    $ ExpRunner --train=False --test=True --lw --config=XXX
"""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import warnings
import os
import importlib
import argparse
import pickle as pkl
from pprint import pprint
import distutils.util
from os.path import join
import glob

import nibabel as nib
import numpy as np
import torch

from tractseg.libs import direction_merger
from tractseg.libs import exp_utils
from tractseg.libs import img_utils
from tractseg.libs import peak_utils 
#from tractseg.libs.system_config import SystemConfig as C
from tractseg.libs import trainer
from tractseg.data.data_loader_training import DataLoaderTraining as DataLoaderTraining2D
from tractseg.data.data_loader_training_3D import DataLoaderTraining as DataLoaderTraining3D
from tractseg.data.data_loader_inference import DataLoaderInference
from tractseg.data import dataset_specific_utils
from tractseg.models.base_model import BaseModel

import neptune
from neptune.utils import stringify_unsupported

from diffusers import StableDiffusionPipeline, UNet2DConditionModel, DDPMScheduler
  
warnings.simplefilter("ignore", UserWarning)  # hide scipy warnings
warnings.simplefilter("ignore", FutureWarning)  # hide h5py warnings
warnings.filterwarnings("ignore", message="numpy.dtype size changed")  # hide Cython benign warning
warnings.filterwarnings("ignore", message="numpy.ufunc size changed")  # hide Cython benign warning


def main():
    parser = argparse.ArgumentParser(description="Train a network on your own data to segment white matter bundles.",
                                        epilog="Written by Jakob Wasserthal. Please reference 'Wasserthal et al. "
                                               "TractSeg - Fast and accurate white matter tract segmentation. "
                                               "https://doi.org/10.1016/j.neuroimage.2018.07.070)'")
    parser.add_argument("--config", metavar="name", help="Name of configuration to use")
    parser.add_argument("--train", metavar="True/False", help="Train network",
                        type=distutils.util.strtobool, default=True)
    parser.add_argument("--test", metavar="True/False", help="Test network",
                        type=distutils.util.strtobool, default=False)
    parser.add_argument("--seg", action="store_true", help="Create binary segmentation")
    parser.add_argument("--probs", action="store_true", help="Create probmap segmentation")
    parser.add_argument("--lw", action="store_true", help="Load weights of pretrained net")
    parser.add_argument("--rt", action="store_true", help="Load pretrained checkpoints for continuing training")
    parser.add_argument("--only_val", action="store_true", help="only run validation")
    parser.add_argument("--en", metavar="name", help="Experiment name")
    parser.add_argument("--fold", metavar="N", help="Which fold to train when doing CrossValidation", type=int)
    parser.add_argument("--verbose", action="store_true", help="Show more intermediate output", default=True)

    parser.add_argument("--with_id", type=str, default=None, help="Neptune run id")
    parser.add_argument("--weights_path", type=str, default="", help="path to weights if not using path in Config")
    parser.add_argument("--data_path", type=str, default=None, help="Neptune run id")
    parser.add_argument("--use_dp", action="store_true", help="whether to activate DataParallel")
    parser.add_argument("--use_ddp", action="store_true", help="whether to activate DistributedDataParallel")
    args = parser.parse_args()

    run = neptune.init_run(
        with_id=args.with_id,  # replace with your actual run id
        project="kjb961013/TractSegVis",  # replace with your actual project path
        api_token="eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI4ZWNlMzk4Ny1hOTVlLTRjMzgtOWI4ZS1hY2FkYTY4MzNhYzMifQ=="  # replace with your API token
        )

    # Config in base.py
    Config = getattr(importlib.import_module("tractseg.experiments.base"), "Config")()
    if args.config:
        # Config.__dict__ does not work properly therefore use this approach
        # Config in custom py file (tractseg/experiments/custom/my_custom_experiment.py)
        Config = getattr(importlib.import_module("tractseg.experiments.custom." + args.config), "Config")()

    if args.en:
        Config.EXP_NAME = args.en # update Config.EXP_NAME
    Config.TRAIN = bool(args.train) # True
    Config.TEST = bool(args.test) # True
    if args.seg:
        Config.SEGMENT = True
    if args.probs:
        Config.GET_PROBS = True
    if args.lw:
        Config.LOAD_WEIGHTS = args.lw
    if args.rt:
        Config.RESUME_TRAINING = args.rt
    if args.fold: # by default: fold= "N" (in ExpRunner)
        Config.CV_FOLD = args.fold
        # print('Config.CV_FOLD after:',Config.CV_FOLD) # 0
        # Consistently run the same fold for all experiments
    if args.only_val: # by default: only_val = False
        Config.ONLY_VAL = True
    if args.with_id:
        Config.WITH_ID = args.with_id
    if args.weights_path:
        Config.WEIGHTS_PATH = args.weights_path
    if args.use_dp:
        Config.USE_DP = args.use_dp
    if args.data_path:
        Config.DATA_PATH = args.data_path
    Config.VERBOSE = args.verbose # by default: verbose = True

    Config.MULTI_PARENT_PATH = join(Config.EXP_PATH, Config.EXP_MULTI_NAME) # by default: C.EXP_PATH = "hcp_exp", Config.EXP_MULTI_NAME=""
    Config.EXP_PATH = join(Config.EXP_PATH, Config.EXP_MULTI_NAME, Config.EXP_NAME) #Config.EXP_NAME="HCP_TEST" -> "hcp_exp/HCP_TEST"
    Config.TRAIN_SUBJECTS, Config.VALIDATE_SUBJECTS, Config.TEST_SUBJECTS = dataset_specific_utils.get_cv_fold(Config) # Config.DATASET = "HCP"

    if Config.RESUME_TRAINING:
        # return path to best weights based on Config.EXP_PATH regardless of the Config.WEIGHTS_PATH
        # You should write the valid Config.EXP_PATH
        print(Config.EXP_PATH)
        Config.WEIGHTS_PATH = exp_utils.get_best_weights_path(Config.EXP_PATH, Config.RESUME_TRAINING) # Config.LOAD_WEIGHTS = False
    elif Config.LOAD_WEIGHTS:
        if Config.WEIGHTS_PATH == "":
            # return path to best weights if you have not specified Config.WEIGHTS_PATH
            Config.WEIGHTS_PATH = exp_utils.get_best_weights_path(Config.EXP_PATH, Config.LOAD_WEIGHTS)
        else: 
            pass # If you have specified Config.WEIGHTS_PATH, it will be loaded at base_model.py

    #Autoset input dimensions based on settings
    # Config.INPUT_DIM = dataset_specific_utils.get_correct_input_dim(Config) # Config.DIM and Config.RESOLUTION are used.
    # Config.INPUT_DIM = (144, 144) (since Config.DIM = "2D" and Config.RESOLUTION = "1.25mm")
    # applies only to HCP data

    # Config = dataset_specific_utils.get_labels_filename(Config)
    # By default: Config.CLASSES = "All", Config.EXPERIMENT_TYPE="tract_segmentation", Config.RESOLUTION='1.25mm' (in base.py)
    # Accordingly, Config.LABELS_FILENAME = "bundle_masks_72"
 

    # if Config.EXPERIMENT_TYPE == "peak_regression":
    #     Config.NR_OF_CLASSES = 3*len(dataset_specific_utils.get_bundle_names(Config.CLASSES)[1:]) # make peaks for each tract (three orientations per tract)
    # else: # <- running this case
    #     Config.NR_OF_CLASSES = len(dataset_specific_utils.get_bundle_names(Config.CLASSES)[1:])
    #     # Config.CLASSES = "All" -> Config.NR_OF_CLASSES = 72, the first component of bundle_names is "Background"
        

    if Config.TRAIN and not Config.ONLY_VAL and not Config.RESUME_TRAINING:
        Config.EXP_PATH = exp_utils.create_experiment_folder(Config.EXP_NAME, Config.MULTI_PARENT_PATH, Config.TRAIN)

    if Config.DIM != "2D":
        Config.EPOCH_MULTIPLIER = 3

    if Config.VERBOSE:
        print("Hyperparameters:")
        exp_utils.print_Configs(Config)

    # with open(join(Config.EXP_PATH, "Hyperparameters.txt"), "w") as f:
    #     Config_dict = {attr: getattr(Config, attr) for attr in dir(Config)
    #                    if not callable(getattr(Config, attr)) and not attr.startswith("__")}
    #     pprint(Config_dict, f)

    # Save hyperparameters in neptune logger
    Config_dict = {attr: getattr(Config, attr) for attr in dir(Config)
                       if not callable(getattr(Config, attr)) and not attr.startswith("__")}  
    Config_dict = {attr: stringify_unsupported(value) if type(value) in ['NoneType', tuple, list] else value for attr, value in Config_dict.items()}
    run["parameters"] = Config_dict
    
    Config = exp_utils.get_correct_labels_type(Config)  # do after saving Hyperparameters as txt

    # we do not need this, since we use neptune to log hyperparameters.
    #pkl.dump(Config, open(join(Config.EXP_PATH, "Hyperparameters.pkl"), "wb"))

    if Config.MODEL == "LatentDiffusionModel":
        scheduler = DDPMScheduler(beta_start=0.0001, beta_end=0.02, num_train_timesteps=1000)
    else:
        scheduler = None

    # Define model
    model = BaseModel(Config)

#    if Config.DIM == "2D":
#        data_loader = DataLoaderTraining2D(Config) 
#    else:
#        data_loader = DataLoaderTraining3D(Config)

    if Config.TRAIN:
        print("Training...")
        trainer.train_model(Config, model, run, scheduler=scheduler)
        # run["train/loss"].append(0.9 ** epoch) # <- why??, which means epoch here?

    # After Training
    if Config.TRAIN and not Config.ONLY_VAL:
        # Have to load other weights, because after training it has the weights of the last epoch
        print("Loading best epoch: {}".format(Config.BEST_EPOCH))
        #Config.WEIGHTS_PATH = Config.EXP_PATH + "/best_weights_ep" + str(Config.BEST_EPOCH) + ".npz"
        Config.WEIGHTS_PATH = sorted(glob.glob(join(Config.EXP_PATH,'best_weights_ep*')))[-1]
        Config.LOAD_WEIGHTS = True
        model.load_model(Config.WEIGHTS_PATH)
        model_test = model
    else: # not Config.TRAIN or Config.ONLY_VAL = True
        # Weight_path already set to best model (when reading program parameters) -> will be loaded automatically
        model_test = model

    if Config.SEGMENT:
        exp_utils.make_dir(join(Config.EXP_PATH, "segmentations"))
        all_subjects = Config.VALIDATE_SUBJECTS
        for subject in all_subjects:
            print("Get_segmentation subject {}".format(subject))
            img_seg, img_y = direction_merger.get_seg_single_img_3_directions(Config, model, subject)
            img_seg = direction_merger.mean_fusion(Config.THRESHOLD, img_seg, probs=False)

            img = nib.Nifti1Image(img_seg.astype(np.uint8),
                                  dataset_specific_utils.get_dwi_affine(Config.DATASET, Config.RESOLUTION))
            nib.save(img, join(Config.EXP_PATH, "segmentations", subject + "_segmentation.nii.gz"))

    if Config.TEST:
        trainer.test_whole_subject(Config, model_test, Config.TEST_SUBJECTS, "test")

    if Config.GET_PROBS:
        exp_utils.make_dir(join(Config.EXP_PATH, "probmaps"))
        all_subjects = Config.VALIDATE_SUBJECTS
        for subject in all_subjects:
            print("Get_probs subject {}".format(subject))
            data_loader = DataLoaderInference(Config, subject=subject)

            #if Config.EXPERIMENT_TYPE == "peak_regression":
            #    img_probs, img_y = trainer.predict_img(Config, model_test, data_loader, probs=True)
            #    img_probs = peak_utils.remove_small_peaks(img_probs, len_thr=0.4)
            #else:
            img_probs, img_y = direction_merger.get_seg_single_img_3_directions(Config, model, subject=subject)
            img_probs = direction_merger.mean_fusion(Config.THRESHOLD, img_probs, probs=True)

            img = nib.Nifti1Image(img_probs, dataset_specific_utils.get_dwi_affine(Config.DATASET, Config.RESOLUTION))
            nib.save(img, join(Config.EXP_PATH, "probmaps", subject + "_peak.nii.gz"))

    # eval_script_path = join(os.path.expanduser("~"), "dev/bsp/eval_nonHCP.py")
    # if os.path.exists(eval_script_path) and not Config.ONLY_VAL and not Config.TEST:
    #     print("Evaluating on non HCP data...")
    #     # Free GPU memory  (2.5GB remaining otherwise)
    #     del model, model_test
    #     torch.cuda.empty_cache()
    #     os.system("python " + eval_script_path + " " + Config.EXP_NAME)
 
if __name__ == '__main__':
    main()