#!/bin/bash -l 
#PBS -A NeuroX
#PBS -N swinunetr
#PBS -l select=1:system=polaris
#PBS -l filesystems=home:grand
#PBS -l walltime=1:00:00
#PBS -q debug
#PBS -j oe

module use /soft/modulefiles; module load conda; conda activate masam

cd /grand/NeuroX/junbeom/TractSegVis/TractSeg/

echo 'starting ExpRunner'
./ExpRunner --fold 0 --data_path /grand/NeuroX/junbeom/TractSegVis --config wholeHCP105_experiment_swinunetr --en run_with_wholeHCP105_swinunetr --train True --test True --seg
#./ExpRunner --config wholevisualtract_experiment --en run_with_vis_settings --train True --test True
