#!/bin/bash -l 
#PBS -A NeuroX
#PBS -N tractseg
#PBS -l select=1:system=polaris
#PBS -l filesystems=home:grand
#PBS -l walltime=12:00:00
#PBS -q preemptable
#PBS -j oe

module use /soft/modulefiles; module load conda; conda activate masam

cd /grand/NeuroX/junbeom/TractSegVis/TractSeg/

# Use 3D volume (whole sequences) for training MASAM model
./ExpRunner --data_path /grand/NeuroX/junbeom/TractSegVis --config Zenedo_experiment_MASAM_x13 --en run_with_default_settings_MASAM_x13 --train True --test True  --lw  # --use_dp #--only_val #--seg

#./ExpRunner --config wholevisualtract_experiment --en run_with_vis_settings --train True --test True
