#!/bin/bash -l 
#PBS -A NeuroX
#PBS -N mednextB
#PBS -l select=1:system=polaris
#PBS -l filesystems=home:grand
#PBS -l walltime=24:00:00
#PBS -q preemptable
#PBS -j oe

module use /soft/modulefiles; module load conda; conda activate masam

cd /grand/NeuroX/junbeom/TractSegVis/TractSeg/

export MASTER_ADDR=`/bin/hostname -s`
export NNODES=`wc -l < $PBS_NODEFILE`
export NRANKS_PER_NODE=$(nvidia-smi -L | wc -l) # should be 1,2 when you test the number of gpus less than 4

#export TORCHINDUCTOR_COMPILE_THREADS=1
#export TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_$RANK

NTOTRANKS=$(( NNODES * NRANKS_PER_NODE ))
echo "NUM_OF_NODES= ${NNODES} TOTAL_NUM_RANKS= ${NTOTRANKS} RANKS_PER_NODE= ${NRANKS_PER_NODE}"

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1

NDEPTH=16

CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 0 --data_path /grand/NeuroX/junbeom/TractSegVis --config wholeHCP_experiment_mednext3D --en wholeHCP_experiment_mednext3D_x20 --train True --test True --seg --rt --with_id TRAC-1091 &
sleep 30
CUDA_VISIBLE_DEVICES=1 ./ExpRunner --fold 1 --data_path /grand/NeuroX/junbeom/TractSegVis --config wholeHCP_experiment_mednext3D --en wholeHCP_experiment_mednext3D_x21 --train True --test True --seg --rt --with_id TRAC-1092 &
sleep 30
CUDA_VISIBLE_DEVICES=2 ./ExpRunner --fold 2 --data_path /grand/NeuroX/junbeom/TractSegVis --config wholeHCP_experiment_mednext3D --en wholeHCP_experiment_mednext3D_x22 --train True --test True --seg --rt --with_id TRAC-1093 &
sleep 30
CUDA_VISIBLE_DEVICES=3 ./ExpRunner --fold 3 --data_path /grand/NeuroX/junbeom/TractSegVis --config wholeHCP_experiment_mednext3D --en wholeHCP_experiment_mednext3D_x23 --train True --test True --seg --rt --with_id TRAC-1094 &
wait