#!/bin/bash -l 
#PBS -A NeuroX
#PBS -N tractseg
#PBS -l select=1:system=polaris
#PBS -l filesystems=home:grand
#PBS -l walltime=24:00:00
#PBS -q preemptable
#PBS -j oe

module use /soft/modulefiles; module load conda; conda activate masam

cd /grand/NeuroX/junbeom/TractSegVis/TractSeg/


./ExpRunner --fold 0 --data_path /grand/NeuroX/junbeom/TractSegVis --config wholeHCP_experiment_TractSeg --en wholeHCP_experiment_TractSeg_x12 --train False --test True --only_val --lw #--seg 
#./ExpRunner --config wholevisualtract_experiment --en run_with_vis_settings --train True --test True
