#!/bin/bash -l 
#PBS -A NeuroX
#PBS -N swinunetr
#PBS -l select=1:system=polaris
#PBS -l filesystems=home:grand
#PBS -l walltime=24:00:00
#PBS -q preemptable
#PBS -j oe

module use /soft/modulefiles; module load conda; conda activate masam

cd /grand/NeuroX/junbeom/TractSegVis/TractSeg/
TORCHINDUCTOR_COMPILE_THREADS=1
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1

# training
CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 0 --data_path /grand/NeuroX/junbeom/TractSegVis --config Ping_experiment_swinunetr --en run_with_Ping_swinunetr --train True --test True & #--rt --with_id TRAC-444
sleep 20
CUDA_VISIBLE_DEVICES=1 ./ExpRunner --fold 1 --data_path /grand/NeuroX/junbeom/TractSegVis --config Ping_experiment_swinunetr --en run_with_Ping_swinunetr --train True --test True & #--rt --with_id TRAC-444
sleep 20
CUDA_VISIBLE_DEVICES=2 ./ExpRunner --fold 2 --data_path /grand/NeuroX/junbeom/TractSegVis --config Ping_experiment_swinunetr --en run_with_Ping_swinunetr --train True --test True & #--rt --with_id TRAC-444
sleep 20
CUDA_VISIBLE_DEVICES=3 ./ExpRunner --fold 3 --data_path /grand/NeuroX/junbeom/TractSegVis --config Ping_experiment_swinunetr --en run_with_Ping_swinunetr --train True --test True & #--rt --with_id TRAC-444
wait

# inference only
#./ExpRunner --fold 0 --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_swinunetr --en run_with_CamCan_swinunetr --train False --test True --lw --weights_path /grand/NeuroX/junbeom/TractSegVis/TractSeg/hcp_exp/run_with_wholeHCP_swinunetr_x11/best_weights_ep67.npz
#./ExpRunner --config wholevisualtract_experiment --en run_with_vis_settings --train True --test True
