#!/bin/bash -l 
#PBS -A NeuroX
#PBS -N tractseg
#PBS -l select=1:system=polaris
#PBS -l filesystems=home:grand
#PBS -l walltime=24:00:00
#PBS -q preemptable
#PBS -j oe

module use /soft/modulefiles; module load conda; conda activate masam

cd /grand/NeuroX/junbeom/TractSegVis/TractSeg/

# try 128/128 spatial dim with slice_direction="y"
./ExpRunner --fold 0 --weights_path "/grand/NeuroX/junbeom/MA-SAM/MA-SAM/checkpoints/sam_vit_l_0b3195.pth" --data_path /grand/NeuroX/junbeom/TractSegVis --config wholeHCP_experiment_MASAM3D_x3 --en run_with_wholeHCP_MASAM3D --train True --test True --seg --lw
#./ExpRunner --config wholevisualtract_experiment --en run_with_vis_settings --train True --test True
