#!/bin/bash -l 
#PBS -A NeuroX
#PBS -N swinunetr3D
#PBS -l select=1:system=polaris
#PBS -l filesystems=home:grand
#PBS -l walltime=24:00:00
#PBS -q preemptable
#PBS -j oe

module use /soft/modulefiles; module load conda; conda activate masam

cd /grand/NeuroX/junbeom/TractSegVis/TractSeg/

export MASTER_ADDR=`/bin/hostname -s`
export NNODES=`wc -l < $PBS_NODEFILE`
export NRANKS_PER_NODE=$(nvidia-smi -L | wc -l) # should be 1,2 when you test the number of gpus less than 4
NTOTRANKS=$(( NNODES * NRANKS_PER_NODE ))
echo "NUM_OF_NODES= ${NNODES} TOTAL_NUM_RANKS= ${NTOTRANKS} RANKS_PER_NODE= ${NRANKS_PER_NODE}"

NDEPTH=16

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1

#SwiunUNETR3D
#CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 0 --data_path /grand/NeuroX/junbeom/TractSegVis --config wholeHCP_experiment_swinunetr3D --en run_with_wholeHCP_swinunetr3D --train True --test True --seg --num_processes 2 --gradient_clip 1 #--rt --with_id TRAC-1079 & #" #--rt --with_id TRAC-444
#sleep 20
CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 1 --data_path /grand/NeuroX/junbeom/TractSegVis --config wholeHCP_experiment_swinunetr3D --en run_with_wholeHCP_swinunetr3D --train True --test True --seg --num_processes 2 --feature_size 24 & # --gradient_clip 1 #--rt --with_id TRAC-1080 & #--rt --with_id TRAC-470
sleep 20
CUDA_VISIBLE_DEVICES=1 ./ExpRunner --fold 2 --data_path /grand/NeuroX/junbeom/TractSegVis --config wholeHCP_experiment_swinunetr3D --en run_with_wholeHCP_swinunetr3D --train True --test True --seg --num_processes 2 --feature_size 24 & # --gradient_clip 1 --rt --with_id TRAC-1082 &
sleep 20
CUDA_VISIBLE_DEVICES=2 ./ExpRunner --fold 1 --data_path /grand/NeuroX/junbeom/TractSegVis --config wholeHCP105_experiment_swinunetr3D --en run_with_wholeHCP105_swinunetr3D --train True --test True --seg --num_processes 2 --feature_size 24 & # --gradient_clip 1 #--rt --with_id TRAC-1080 & #--rt --with_id TRAC-470
sleep 20
CUDA_VISIBLE_DEVICES=3 ./ExpRunner --fold 2 --data_path /grand/NeuroX/junbeom/TractSegVis --config wholeHCP105_experiment_swinunetr3D --en run_with_wholeHCP105_swinunetr3D --train True --test True --seg --num_processes 2 --feature_size 24 & # --gradient_clip 1 --rt --with_id TRAC-1082 &
wait

#./ExpRunner --fold 2 --data_path /grand/NeuroX/junbeom/TractSegVis --config wholeHCP_experiment_swinunetr3D --en run_with_wholeHCP_swinunetr3D --train True --test True --seg #--rt --with_id TRAC-471

# resume training
#Command="./ExpRunner --fold 0 --data_path /grand/NeuroX/junbeom/TractSegVis --config wholeHCP_experiment_swinunetr3D --en run_with_wholeHCP_swinunetr3D_x12 --train True --test True --seg --rt --with_id TRAC-717"
#./ExpRunner --fold 1 --data_path /grand/NeuroX/junbeom/TractSegVis --config wholeHCP_experiment_swinunetr3D --en run_with_wholeHCP_swinunetr3D_x1 --train True --test True --seg --rt --with_id TRAC-672

#set_affinity_cmd="./scripts/polaris/set_affinity_gpu_polaris_profiling.sh"
#torchrun --nnodes=1 --nproc_per_node=4 $Command
#mpiexec -n ${NTOTRANKS} --ppn ${NRANKS_PER_NODE} --depth=${NDEPTH} --cpu-bind=depth $set_affinity_cmd $Command 