#!/bin/bash -l 
#PBS -A NeuroX
#PBS -N tractseg
#PBS -l select=1:system=polaris
#PBS -l filesystems=home:grand
#PBS -l walltime=15:00:00
#PBS -q preemptable
#PBS -j oe

module use /soft/modulefiles; module load conda; conda activate masam

cd /grand/NeuroX/junbeom/TractSegVis/TractSeg/

#./ExpRunner --fold 1 --config Zenedo_experiment_sorted_aligned_x4 --en run_with_default_settings_sorted_aligned_x13 --train True --test True --seg --rt --with_id TRAC-494
./ExpRunner --fold 2 --config Zenedo_experiment_sorted_aligned_x4 --en run_with_default_settings_sorted_aligned_x14 --train True --test True --seg --rt --with_id TRAC-498
#./ExpRunner --config wholevisualtract_experiment --en run_with_vis_settings --train True --test True
