#!/bin/bash -l 
#PBS -A NeuroX
#PBS -N MASAM3D
#PBS -l select=1:system=polaris
#PBS -l filesystems=home:grand
#PBS -l walltime=1:00:00
#PBS -q debug
#PBS -j oe

module use /soft/modulefiles; module load conda; conda activate masam

cd /grand/NeuroX/junbeom/TractSegVis/TractSeg/

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1

# training
# CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 0 --weights_path /grand/NeuroX/junbeom/MA-SAM/MA-SAM/checkpoints/sam_vit_l_0b3195.pth --lw --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_MASAM3D_x1 --en CamCan_experiment_MASAM3D --train True --test True --seg --gradient_clip 1 & 
# sleep 20
# CUDA_VISIBLE_DEVICES=1 ./ExpRunner --fold 1 --weights_path /grand/NeuroX/junbeom/MA-SAM/MA-SAM/checkpoints/sam_vit_l_0b3195.pth --lw --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_MASAM3D_x1 --en CamCan_experiment_MASAM3D --train True --test True --seg --gradient_clip 1 & 
# sleep 20
# CUDA_VISIBLE_DEVICES=2 ./ExpRunner --fold 2 --weights_path /grand/NeuroX/junbeom/MA-SAM/MA-SAM/checkpoints/sam_vit_l_0b3195.pth --lw --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_MASAM3D_x1 --en CamCan_experiment_MASAM3D --train True --test True --seg --gradient_clip 1 & 
# sleep 20
# CUDA_VISIBLE_DEVICES=3 ./ExpRunner --fold 3 --weights_path /grand/NeuroX/junbeom/MA-SAM/MA-SAM/checkpoints/sam_vit_l_0b3195.pth --lw --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_MASAM3D_x1 --en CamCan_experiment_MASAM3D --train True --test True --seg --gradient_clip 1 & 
# wait


# inference only
#./ExpRunner --fold 0 --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_TractSeg --en CamCan_experiment_TractSeg --train False --test True --lw --weights_path /grand/NeuroX/junbeom/TractSegVis/TractSeg/hcp_exp/wholeHCP_experiment_TractSeg_x14/best_weights_ep73.npz #--seg 
#./ExpRunner --config wholevisualtract_experiment --en run_with_vis_settings --train True --test True

# from HCP+CAMCAN+PING
CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 0 --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_MASAM3D_x1 --en CamCan_experiment_MASAM3D --train False --test True --lw --weights_path /grand/NeuroX/junbeom/TractSegVis/TractSeg/hcp_exp/HCP_CamCan_Ping_experiment_MASAM3D_x8/best_weights_ep29.npz & # --seg --rt --with_id TRAC-469
sleep 20
# 
# CUDA_VISIBLE_DEVICES=1 ./ExpRunner --fold 2 --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_MASAM3D_x1 --en CamCan_experiment_MASAM3D --train False --test True --lw --weights_path /grand/NeuroX/junbeom/TractSegVis/TractSeg/hcp_exp/wholeHCP105_experiment_mednext3D_x22/best_weights_ep191.npz  & # --seg --rt --with_id TRAC-469
# sleep 20
wait