#!/bin/bash -l 
#PBS -A NeuroX
#PBS -N tractseg
#PBS -l select=1:system=polaris
#PBS -l filesystems=home:grand
#PBS -l walltime=24:00:00
#PBS -q preemptable
#PBS -j oe

module use /soft/modulefiles; module load conda; conda activate masam

cd /grand/NeuroX/junbeom/TractSegVis/TractSeg/

#./ExpRunner --fold 0 --config Zenedo_experiment_MASAM_x10 --en run_with_default_settings_MASAM --train True --test True --seg --lw
#./ExpRunner --fold 1 --config Zenedo_experiment_MASAM_x10 --en run_with_default_settings_MASAM --train True --test True --seg --lw
./ExpRunner --fold 2 --config Zenedo_experiment_MASAM_x10 --en run_with_default_settings_MASAM --train True --test True --seg --lw
