#!/bin/bash -l 
#PBS -A NeuroX
#PBS -N tractseg3D
#PBS -l select=1:system=polaris
#PBS -l filesystems=home:grand
#PBS -l walltime=24:00:00
#PBS -q preemptable
#PBS -j oe

module use /soft/modulefiles; module load conda; conda activate masam

cd /grand/NeuroX/junbeom/TractSegVis/TractSeg/

# training
CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 0 --data_path /grand/NeuroX/junbeom/TractSegVis --config Ping_experiment_TractSeg3D --en Ping_experiment_TractSeg3D --train True --test True --seg &
CUDA_VISIBLE_DEVICES=1 ./ExpRunner --fold 1 --data_path /grand/NeuroX/junbeom/TractSegVis --config Ping_experiment_TractSeg3D --en Ping_experiment_TractSeg3D --train True --test True --seg &
CUDA_VISIBLE_DEVICES=2 ./ExpRunner --fold 2 --data_path /grand/NeuroX/junbeom/TractSegVis --config Ping_experiment_TractSeg3D --en Ping_experiment_TractSeg3D --train True --test True --seg &
CUDA_VISIBLE_DEVICES=3 ./ExpRunner --fold 3 --data_path /grand/NeuroX/junbeom/TractSegVis --config Ping_experiment_TractSeg3D --en Ping_experiment_TractSeg3D --train True --test True --seg &
wait

# inference only
#./ExpRunner --fold 0 --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_TractSeg3D --en CamCan_experiment_TractSeg3D --train False --test True --lw --weights_path /grand/NeuroX/junbeom/TractSegVis/TractSeg/hcp_exp/wholeHCP_experiment_TractSeg3D_x14/best_weights_ep15.npz #--seg #--rt --with_id TRAC-469
#./ExpRunner --config wholevisualtract_experiment --en run_with_vis_settings --train True --test True
