#!/bin/bash -l 
#PBS -A NeuroX
#PBS -N mednextB
#PBS -l select=1:system=polaris
#PBS -l filesystems=home:grand
#PBS -l walltime=24:00:00
#PBS -q preemptable
#PBS -j oe

module use /soft/modulefiles; module load conda; conda activate masam

cd /grand/NeuroX/junbeom/TractSegVis/TractSeg/

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1

# training
# 3D SwinUNETR
# ./ExpRunner --fold 0 --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_mednext3D --en CamCan_experiment_mednext3D --train True --test True --seg --num_processes 4 & #--rt --with_id TRAC-444
# sleep 20

#./ExpRunner --fold 1 --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_mednext3D --en CamCan_experiment_mednext3D --train True --test True --seg --num_processes 4 #& #--rt --with_id TRAC-444
#sleep 20

./ExpRunner --fold 2 --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_mednext3D --en CamCan_experiment_mednext3D --train True --test True --seg --num_processes 4 #& #--rt --with_id TRAC-444
#wait

# inference only
#./ExpRunner --fold 1 --data_path /grand/NeuroX/junbeom/TractSegVis --config wholeHCP_experiment_swinunetr3D --en run_with_wholeHCP_swinunetr3D --train True --test True --seg #--rt --with_id TRAC-470
#./ExpRunner --fold 2 --data_path /grand/NeuroX/junbeom/TractSegVis --config wholeHCP_experiment_swinunetr3D --en run_with_wholeHCP_swinunetr3D --train True --test True --seg #--rt --with_id TRAC-471