#!/bin/bash -l 
#PBS -A NeuroX
#PBS -N mednextB
#PBS -l select=1:system=polaris
#PBS -l filesystems=home:grand
#PBS -l walltime=1:00:00
#PBS -q preemptable
#PBS -j oe

module use /soft/modulefiles; module load conda; conda activate masam

cd /grand/NeuroX/junbeom/TractSegVis/TractSeg/

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1

# training
# 3D SwinUNETR
# ./ExpRunner --fold 0 --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_mednext3D --en CamCan_experiment_mednext3D --train True --test True --seg --num_processes 4 & #--rt --with_id TRAC-444
# sleep 20

#./ExpRunner --fold 1 --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_mednext3D --en CamCan_experiment_mednext3D --train True --test True --seg --num_processes 4 #& #--rt --with_id TRAC-444
#sleep 20

#./ExpRunner --fold 2 --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_mednext3D --en CamCan_experiment_mednext3D --train True --test True --seg --num_processes 4 #& #--rt --with_id TRAC-444
#wait

# inference only
#./ExpRunner --fold 1 --data_path /grand/NeuroX/junbeom/TractSegVis --config wholeHCP_experiment_swinunetr3D --en run_with_wholeHCP_swinunetr3D --train True --test True --seg #--rt --with_id TRAC-470
#./ExpRunner --fold 2 --data_path /grand/NeuroX/junbeom/TractSegVis --config wholeHCP_experiment_swinunetr3D --en run_with_wholeHCP_swinunetr3D --train True --test True --seg #--rt --with_id TRAC-471

# from HCP+CAMCAN+PING
CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 0 --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_mednext3D --en CamCan_experiment_mednext3D --train False --test True --lw --weights_path /grand/NeuroX/junbeom/TractSegVis/TractSeg/hcp_exp/HCP_CamCan_Ping_experiment_mednext3D/best_weights_ep18.npz & # --seg --rt --with_id TRAC-469
sleep 20
CUDA_VISIBLE_DEVICES=1 ./ExpRunner --fold 1 --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_mednext3D --en CamCan_experiment_mednext3D --train False --test True --lw --weights_path /grand/NeuroX/junbeom/TractSegVis/TractSeg/hcp_exp/HCP_CamCan_Ping_experiment_mednext3D_x1/best_weights_ep16.npz & # --seg --rt --with_id TRAC-469
sleep 20
CUDA_VISIBLE_DEVICES=2 ./ExpRunner --fold 2 --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_mednext3D --en CamCan_experiment_mednext3D --train False --test True --lw --weights_path /grand/NeuroX/junbeom/TractSegVis/TractSeg/hcp_exp/HCP_CamCan_Ping_experiment_mednext3D_x2/best_weights_ep14.npz & # --seg --rt --with_id TRAC-469
sleep 20

# from HCP all
CUDA_VISIBLE_DEVICES=3 ./ExpRunner --fold 0 --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_mednext3D --en CamCan_experiment_mednext3D --train False --test True --lw --weights_path /grand/NeuroX/junbeom/TractSegVis/TractSeg/hcp_exp/wholeHCP105_experiment_mednext3D_x20/best_weights_ep76.npz & # --seg --rt --with_id TRAC-469
wait

CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 1 --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_mednext3D --en CamCan_experiment_mednext3D --train False --test True --lw --weights_path /grand/NeuroX/junbeom/TractSegVis/TractSeg/hcp_exp/wholeHCP105_experiment_mednext3D_x21/best_weights_ep160.npz  & # --seg --rt --with_id TRAC-469
sleep 20
CUDA_VISIBLE_DEVICES=1 ./ExpRunner --fold 2 --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_mednext3D --en CamCan_experiment_mednext3D --train False --test True --lw --weights_path /grand/NeuroX/junbeom/TractSegVis/TractSeg/hcp_exp/wholeHCP105_experiment_mednext3D_x22/best_weights_ep191.npz  & # --seg --rt --with_id TRAC-469
sleep 20
wait