#!/bin/bash -l 
#PBS -A NeuroX
#PBS -N mednextB
#PBS -l select=1:system=polaris
#PBS -l filesystems=home:grand
#PBS -l walltime=24:00:00
#PBS -q preemptable
#PBS -j oe

module use /soft/modulefiles; module load conda; conda activate masam

cd /grand/NeuroX/junbeom/TractSegVis/TractSeg/

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1

# training
CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 0 --data_path /grand/NeuroX/junbeom/TractSegVis --config HCP_CamCan_Ping_experiment_mednext3D --en HCP_CamCan_Ping_experiment_mednext3D --train True --test True --seg --rt --with_id TRAC-1069 &
sleep 20
CUDA_VISIBLE_DEVICES=1 ./ExpRunner --fold 1 --data_path /grand/NeuroX/junbeom/TractSegVis --config HCP_CamCan_Ping_experiment_mednext3D --en HCP_CamCan_Ping_experiment_mednext3D_x1 --train True --test True --seg --rt --with_id TRAC-1070 &
sleep 20
CUDA_VISIBLE_DEVICES=2 ./ExpRunner --fold 2 --data_path /grand/NeuroX/junbeom/TractSegVis --config HCP_CamCan_Ping_experiment_mednext3D --en HCP_CamCan_Ping_experiment_mednext3D_x2 --train True --test True --seg --rt --with_id TRAC-1071 &
sleep 20
CUDA_VISIBLE_DEVICES=3 ./ExpRunner --fold 3 --data_path /grand/NeuroX/junbeom/TractSegVis --config HCP_CamCan_Ping_experiment_mednext3D --en HCP_CamCan_Ping_experiment_mednext3D_x3 --train True --test True --seg --rt --with_id TRAC-1072 &
wait

# inference only
#./ExpRunner --fold 0 --data_path /grand/NeuroX/junbeom/TractSegVis --config CamCan_experiment_TractSeg --en CamCan_experiment_TractSeg --train False --test True --lw --weights_path /grand/NeuroX/junbeom/TractSegVis/TractSeg/hcp_exp/wholeHCP_experiment_TractSeg_x14/best_weights_ep73.npz #--seg 
#./ExpRunner --config wholevisualtract_experiment --en run_with_vis_settings --train True --test True
