#!/bin/bash -l 

source /home/junb/miniconda3/bin/activate
conda activate masam

cd /mnt/scratch/junb/TractSegVis/TractSeg

DATA_PATH="/mnt/scratch/junb/TractSegVis/"

#  HCP to HCP
# # TractSeg2D from all HCP (same)
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg --en HCP_to_HCP_experiment_TractSeg_inference_x1 --train False --test False --lw  --weights_path /mnt/storage/junb/hcp_ecp/wholeHCP_experiment_TractSeg_x14/best_weights_ep73.npz --seg &
# sleep 20
# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg --en HCP_to_HCP_experiment_TractSeg_inference_x2 --train False --test False --lw  --weights_path /mnt/storage/junb/hcp_ecp/wholeHCP_experiment_TractSeg_x1/best_weights_ep68.npz --seg &
# sleep 20
# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg --en HCP_to_HCP_experiment_TractSeg_inference_x3 --train False --test False --lw  --weights_path /mnt/storage/junb/hcp_ecp/wholeHCP_experiment_TractSeg_x15/best_weights_ep52.npz --seg &
# sleep 20


# # TractSeg 3D from HCP (same)
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg3D --en HCP_to_HCP_experiment_TractSeg3D_inference_x1 --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/wholeHCP_experiment_TractSeg3D_x14/best_weights_ep17.npz --seg & 
# sleep 20
# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg3D --en HCP_to_HCP_experiment_TractSeg3D_inference_x2  --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/wholeHCP_experiment_TractSeg3D_x1/best_weights_ep13.npz --seg & 
# sleep 20
# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg3D --en HCP_to_HCP_experiment_TractSeg3D_inference_x3  --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/wholeHCP_experiment_TractSeg3D_x15/best_weights_ep19.npz --seg & 
# wait

# # # swinunetr from HCP (same)
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr --en HCP_to_HCP_experiment_swinunetr_inference_x1 --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_wholeHCP_swinunetr_x11/best_weights_ep67.npz --seg & 
# sleep 20
# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr --en HCP_to_HCP_experiment_swinunetr_inference_x2 --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_wholeHCP_swinunetr_x12/best_weights_ep28.npz --seg & 
# sleep 20
# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr --en HCP_to_HCP_experiment_swinunetr_inference_x3 --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_wholeHCP_swinunetr_x13/best_weights_ep22.npz --seg & 
# sleep 20
# wait

# # # swinunetr3D from HCP (same)
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr3D --en HCP_to_HCP_experiment_swinunetr3D_inference_x1  --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_wholeHCP_swinunetr3D_x12/best_weights_ep26.npz --seg & 
# sleep 20
# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr3D --en HCP_to_HCP_experiment_swinunetr3D_inference_x2  --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_wholeHCP_swinunetr3D_x80/best_weights_ep6.npz --seg & 
# sleep 20
# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr3D --en HCP_to_HCP_experiment_swinunetr3D_inference_x3  --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_wholeHCP_swinunetr3D_x81/best_weights_ep6.npz --seg & 
# wait

# # # # MASAM3D from HCP (same)
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_MASAM3D_x1 --en HCP_to_HCP_experiment_MASAM3D_inference_x1 --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_wholeHCP_MASAM3D_x22/best_weights_ep28.npz --seg & 
# sleep 20
# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_MASAM3D_x1 --en HCP_to_HCP_experiment_MASAM3D_inference_x2 --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_wholeHCP_MASAM3D_x1/best_weights_ep27.npz  --seg &
# sleep 20
# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_MASAM3D_x1 --en HCP_to_HCP_experiment_MASAM3D_inference_x3 --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_wholeHCP_MASAM3D_x23/best_weights_ep37.npz --seg &
# sleep 20

# # # MedNext3D from HCP (same)
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_mednext3D --en HCP_to_HCP_experiment_mednext3D_inference_x1  --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/wholeHCP_experiment_mednext3D_x20/best_weights_ep17.npz --seg & 
# sleep
# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_mednext3D --en HCP_to_HCP_experiment_mednext3D_inference_x2  --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/wholeHCP_experiment_mednext3D_x21/best_weights_ep18.npz --seg & 
# sleep 20
# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_mednext3D --en HCP_to_HCP_experiment_mednext3D_inference_x3  --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/wholeHCP_experiment_mednext3D_x22/best_weights_ep19.npz --seg & 
# wait


# # HCP+PING+CAMCAN to HCP
# # TractSeg 2D 
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg --en HCP_CamCan_PING_to_HCP_experiment_TractSeg_inference_x1 --train False --test False --lw  --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_TractSeg_x2/best_weights_ep22.npz --seg &
# sleep 20
# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg --en HCP_CamCan_PING_to_HCP_experiment_TractSeg_inference_x2 --train False --test False --lw  --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_TractSeg_x3/best_weights_ep25.npz --seg &
# sleep 20
# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg --en HCP_CamCan_PING_to_HCP_experiment_TractSeg_inference_x3 --train False --test False --lw  --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_TractSeg_x4/best_weights_ep26.npz --seg &
# sleep 20


# # TractSeg3D 
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg3D --en HCP_CamCan_PING_to_HCP_experiment_TractSeg3D_inference_x1 --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_TractSeg3D_x3/best_weights_ep7.npz  --seg & 
# sleep 20
# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg3D --en HCP_CamCan_PING_to_HCP_experiment_TractSeg3D_inference_x2 --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_TractSeg3D_x4/best_weights_ep8.npz --seg & 
# sleep 20
# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg3D --en HCP_CamCan_PING_to_HCP_experiment_TractSeg3D_inference_x3 --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_TractSeg3D_x5/best_weights_ep7.npz --seg & 
# wait

# # # swinunetr2D from HCP+PING+CAMCAN
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr --en HCP_CamCan_PING_to_HCP_experiment_swinunetr_inference_x1  --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_swinunetr_x4/best_weights_ep27.npz  --seg & 
# sleep 20
# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr --en HCP_CamCan_PING_to_HCP_experiment_swinunetr_inference_x2  --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_swinunetr_x5/best_weights_ep25.npz --seg & 
# sleep 20
# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr --en HCP_CamCan_PING_to_HCP_experiment_swinunetr_inference_x3  --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_swinunetr_x6/best_weights_ep33.npz --seg & 
#wait
# sleep 20

# # # swinunetr3D from HCP+CAMCAN+PING
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr3D --en HCP_CamCan_PING_to_HC_experiment_swinunetr3D_inference_x1  --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_swinunetr3D_x2/best_weights_ep7.npz --seg & 
# sleep 20
 ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr3D --en HCP_CamCan_PING_to_HCP_experiment_swinunetr3D_inference_x2  --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_swinunetr3D_x3/best_weights_ep8.npz --seg & 
sleep 20
./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr3D --en HCP_CamCan_PING_to_HCP_experiment_swinunetr3D_inference_x3  --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_swinunetr3D_x4/best_weights_ep7.npz --seg & 
wait

# # # MASAM3D from HCP+CAMCAN+PING
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_MASAM3D_x1 --en HCP_CamCan_PING_to_HCP_experiment_MASAM3D_inference_x1  --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_MASAM3D_x8/best_weights_ep29.npz --seg & 
# sleep 20
# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_MASAM3D_x1 --en HCP_CamCan_PING_to_HCP_experiment_MASAM3D_inference_x2  --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_MASAM3D_x9/best_weights_ep25.npz  --seg &
# sleep 20
# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_MASAM3D_x1 --en HCP_CamCan_PING_to_HCP_experiment_MASAM3D_inference_x3  --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_MASAM3D_x10/best_weights_ep20.npz --seg &
# sleep 20

# # MedNeXt3D from HCP+CAMCAN+PING
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_mednext3D --en HCP_CamCan_PING_to_HCP_experiment_mednext3D_inference_x1  --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_mednext3D/best_weights_ep18.npz --seg & 
# sleep 20
# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_mednext3D --en HCP_CamCan_PING_to_HCP_experiment_mednext3D_inference_x2  --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_mednext3D_x1/best_weights_ep16.npz --seg & 
# sleep 20

# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_mednext3D --en HCP_CamCan_PING_to_HCP_experiment_mednext3D_inference_x3  --train False --test False --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_mednext3D_x2/best_weights_ep14.npz --seg & 
# wait
# 여기까지는 --seg로 들어감.


# # From PING to HCP
# # TractSeg2D from PING to HCP
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg --en PING_to_HCP_experiment_TractSeg_inference_x1 --train False --test False --lw  --weights_path /mnt/storage/junb/hcp_ecp/Ping_experiment_TractSeg_x9/best_weights_ep105.npz --seg &
# sleep 20
# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg --en PING_to_HCP_experiment_TractSeg_inference_x2 --train False --test False --lw  --weights_path /mnt/storage/junb/hcp_ecp/Ping_experiment_TractSeg_x10/best_weights_ep105.npz --seg &
# sleep 20
# # 여기서부터 probs_map이 만들어지기 시작
# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg --en PING_to_HCP_experiment_TractSeg_inference_x3 --train False --test False --lw  --weights_path /mnt/storage/junb/hcp_ecp/Ping_experiment_TractSeg_x12/best_weights_ep193.npz --seg &
# sleep 20

# #TractSeg3D from PING to HCP
#./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg3D --en PING_to_HCP_experiment_TractSeg3D_inference_x1 --train False --test True --lw  --weights_path /mnt/storage/junb/hcp_ecp/Ping_experiment_TractSeg3D_x1/best_weights_ep51.npz --seg &
#sleep 20
#./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg3D --en PING_to_HCP_experiment_TractSeg3D_inference_x2 --train False --test True --lw  --weights_path /mnt/storage/junb/hcp_ecp/Ping_experiment_TractSeg3D_x2/best_weights_ep53.npz --seg &
#sleep 20
#./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg3D --en PING_to_HCP_experiment_TractSeg3D_inference_x3 --train False --test True --lw  --weights_path /mnt/storage/junb/hcp_ecp/Ping_experiment_TractSeg3D_x3/best_weights_ep35.npz --seg &
#wait
# #swinunetr from PING to HCP
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr --en PING_to_HCP_experiment_swinunetr_inference_x1 --train False --test False --lw  --weights_path /mnt/storage/junb/hcp_ecp/run_with_Ping_swinunetr_x17/best_weights_ep174.npz --seg &
# sleep 20
# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr --en PING_to_HCP_experiment_swinunetr_inference_x2 --train False --test False --lw  --weights_path /mnt/storage/junb/hcp_ecp/run_with_Ping_swinunetr_x18/best_weights_ep104.npz --seg &
# sleep 20
# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr --en PING_to_HCP_experiment_swinunetr_inference_x3 --train False --test False --lw  --weights_path /mnt/storage/junb/hcp_ecp/run_with_Ping_swinunetr_x19/best_weights_ep111.npz --seg &
# sleep 20

# #swinunetr3D from PING to HCP
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr3D --en PING_to_HCP_experiment_swinunetr3D_inference_x1 --train False --test False --lw  --weights_path /mnt/storage/junb/hcp_ecp/run_with_Ping_swinunetr3D_x7/best_weights_ep36.npz --seg &
# sleep 20
# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr3D --en PING_to_HCP_experiment_swinunetr3D_inference_x2 --train False --test False --lw  --weights_path /mnt/storage/junb/hcp_ecp/run_with_Ping_swinunetr3D_x8/best_weights_ep33.npz --seg &
# sleep 20
# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr3D --en PING_to_HCP_experiment_swinunetr3D_inference_x3 --train False --test False --lw  --weights_path /mnt/storage/junb/hcp_ecp/run_with_Ping_swinunetr3D_x9/best_weights_ep29.npz --seg &
# wait

# #masam3D from PING to HCP
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_MASAM3D_x1 --en PING_to_HCP_experiment_MASAM3D_inference_x1 --train False --test False --lw  --weights_path /mnt/storage/junb/hcp_ecp/Ping_experiment_MASAM3D/best_weights_ep38.npz --seg &
# sleep 20
# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_MASAM3D_x1 --en PING_to_HCP_experiment_MASAM3D_inference_x2 --train False --test False --lw  --weights_path /mnt/storage/junb/hcp_ecp/Ping_experiment_MASAM3D_x1/best_weights_ep113.npz --seg &
# sleep 20
# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_MASAM3D_x1 --en PING_to_HCP_experiment_MASAM3D_inference_x3 --train False --test False --lw  --weights_path /mnt/storage/junb/hcp_ecp/Ping_experiment_MASAM3D_x2/best_weights_ep131.npz --seg &
# sleep 20

# #MedNext3D from PING to HCP
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_mednext3D --en PING_to_HCP_experiment_mednext3D_inference_x1 --train False --test False --lw  --weights_path /mnt/storage/junb/hcp_ecp/run_with_Ping_mednext3D/best_weights_ep74.npz --seg &
# sleep 20
# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_mednext3D --en PING_to_HCP_experiment_mednext3D_inference_x2 --train False --test False --lw  --weights_path /mnt/storage/junb/hcp_ecp/run_with_Ping_mednext3D_x1/best_weights_ep40.npz --seg &
# sleep 20
# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_mednext3D --en PING_to_HCP_experiment_mednext3D_inference_x3 --train False --test False --lw  --weights_path /mnt/storage/junb/hcp_ecp/run_with_Ping_mednext3D_x2/best_weights_ep62.npz --seg &
# wait


# # From CamCan to HCP
# # TractSeg2D from CAMCAN
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg --en CamCan_to_HCP_experiment_TractSeg_inference_x1 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/CamCan_experiment_TractSeg_x1/best_weights_ep224.npz --seg &
# sleep 20
# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg --en CamCan_to_HCP_experiment_TractSeg_inference_x2 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/CamCan_experiment_TractSeg_x4/best_weights_ep45.npz --seg &
# sleep 20
# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg --en CamCan_to_HCP_experiment_TractSeg_inference_x3 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/CamCan_experiment_TractSeg_x5/best_weights_ep107.npz --seg &
# sleep 20

# # TractSeg3D from CAMCAN
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg3D --en CamCan_to_HCP_experiment_TractSeg3D_inference_x1 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/CamCan_experiment_TractSeg3D_x1/best_weights_ep58.npz --seg &
# sleep 20

# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg3D --en CamCan_to_HCP_experiment_TractSeg3D_inference_x2 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/CamCan_experiment_TractSeg3D_x6/best_weights_ep16.npz --seg &
# sleep 20

# # TractSeg3D fold1과 fold2는 x6로 동일한 exp_path를 사용함
# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_TractSeg3D --en CamCan_to_HCP_experiment_TractSeg3D_inference_x3 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/CamCan_experiment_TractSeg3D_x6/best_weights_ep16.npz --seg &
# wait


# # SwinUNETR2D from CAMCAN
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr --en CamCan_to_HCP_experiment_swinunetr_inference_x1 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_CamCan_swinunetr_x2/best_weights_ep205.npz --seg &
# sleep 20

# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr --en CamCan_to_HCP_experiment_swinunetr_inference_x2 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_CamCan_swinunetr_x5/best_weights_ep68.npz --seg &
# sleep 20

# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr --en CamCan_to_HCP_experiment_swinunetr_inference_x3 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_CamCan_swinunetr_x6/best_weights_ep65.npz --seg &
# sleep 20

# SwinUNETR3D from CAMCAN
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr3D --en CamCan_to_HCP_experiment_swinunetr3D_inference_x1 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_CamCan_swinunetr3D_x2/best_weights_ep20.npz --seg &
# sleep 20
# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr3D --en CamCan_to_HCP_experiment_swinunetr3D_inference_x2 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_CamCan_swinunetr3D_x6/best_weights_ep13.npz --seg &
# sleep 20
# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_swinunetr3D --en CamCan_to_HCP_experiment_swinunetr3D_inference_x3 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_CamCan_swinunetr3D_x6/best_weights_ep13.npz --seg &
# wait
# SwinUNETR3D fold1과 fold2는 x6로 동일한 exp_path를 사용함

# # MASAM3D from CAMCAN
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_MASAM3D_x1 --en CamCan_to_HCP_experiment_MASAM3D_inference_x1 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/CamCan_experiment_MASAM3D/best_weights_ep45.npz --seg &
# sleep 20
# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_MASAM3D_x1 --en CamCan_to_HCP_experiment_MASAM3D_inference_x2 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/CamCan_experiment_MASAM3D_x1/best_weights_ep36.npz --seg &
# sleep 20

# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_MASAM3D_x1 --en CamCan_to_HCP_experiment_MASAM3D_inference_x3 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/CamCan_experiment_MASAM3D_x2/best_weights_ep50.npz --seg &
# sleep 20


# # MedNext3D from CAMCAN
# ./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP_experiment_mednext3D --en CamCan_to_HCP_experiment_mednext3D_inference_x1 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/CamCan_experiment_mednext3D/best_weights_ep26.npz --seg &
# sleep 20

# ./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP_experiment_mednext3D --en CamCan_to_HCP_experiment_mednext3D_inference_x2 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/CamCan_experiment_mednext3D_x5/best_weights_ep26.npz --seg &
# sleep 20

# ./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP_experiment_mednext3D --en CamCan_to_HCP_experiment_mednext3D_inference_x3 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/CamCan_experiment_mednext3D_x4/best_weights_ep30.npz --seg &
# wait
