#!/bin/bash -l 

source /home/junb/miniconda3/bin/activate
conda activate masam

cd $DATA_PATH/TractSeg

DATA_PATH="$DATA_PATH/"

#  HCP to HCP
# # TractSeg2D from HCP105 (same)
./ExpRunner --fold 0 --data_path $DATA_PATH --config Zenedo_experiment_sorted_aligned_x4 --en Zenedo_to_Zenedo_experiment_TractSeg_inference_x1 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_default_settings_sorted_aligned_x4/best_weights_ep311.npz --seg &
sleep 20
./ExpRunner --fold 1 --data_path $DATA_PATH --config Zenedo_experiment_sorted_aligned_x4 --en Zenedo_to_Zenedo_experiment_TractSeg_inference_x2 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_default_settings_sorted_aligned_x13/best_weights_ep181.npz --seg &
sleep 20
./ExpRunner --fold 2 --data_path $DATA_PATH --config Zenedo_experiment_sorted_aligned_x4 --en Zenedo_to_Zenedo_experiment_TractSeg_inference_x3 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_default_settings_sorted_aligned_x14/best_weights_ep201.npz --seg &
sleep 20

# # TractSeg3D from HCP105 (same)
./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP105_experiment_TractSeg3D --en Zenedo_to_Zenedo_experiment_TractSeg3D_inference_x1 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/wholeHCP105_experiment_TractSeg3D_x11/best_weights_ep95.npz --seg &
sleep 20
./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP105_experiment_TractSeg3D --en Zenedo_to_Zenedo_experiment_TractSeg3D_inference_x2 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/wholeHCP105_experiment_TractSeg3D_x12/best_weights_ep138.npz --seg &
sleep 20
./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP105_experiment_TractSeg3D --en Zenedo_to_Zenedo_experiment_TractSeg3D_inference_x3 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/wholeHCP105_experiment_TractSeg3D_x9/best_weights_ep145.npz --seg &
sleep 20

# # swinunetr from HCP105 (same)
./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP105_experiment_swinunetr --en Zenedo_to_Zenedo_experiment_swinunetr_inference_x1 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_wholeHCP105_swinunetr_x12/best_weights_ep206.npz --seg & 
sleep 20
./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP105_experiment_swinunetr --en Zenedo_to_Zenedo_experiment_swinunetr_inference_x2 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_wholeHCP105_swinunetr_x21/best_weights_ep102.npz --seg & 
sleep 20
./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP105_experiment_swinunetr --en Zenedo_to_Zenedo_experiment_swinunetr_inference_x3 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_wholeHCP105_swinunetr_x22/best_weights_ep197.npz --seg & 
sleep 20
wait

# # swinunetr3D from HCP105 (same)
./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP105_experiment_swinunetr3D --en Zenedo_to_Zenedo_experiment_swinunetr3D_inference_x1  --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_wholeHCP105_swinunetr3D_x15/best_weights_ep117.npz --seg & 
sleep 20
./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP105_experiment_swinunetr3D --en Zenedo_to_Zenedo_experiment_swinunetr3D_inference_x2  --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_wholeHCP105_swinunetr3D_x64/best_weights_ep21.npz --seg & 
sleep 20
./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP105_experiment_swinunetr3D --en Zenedo_to_Zenedo_experiment_swinunetr3D_inference_x3  --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_wholeHCP105_swinunetr3D_x65/best_weights_ep11.npz --seg & 
wait

# # # # MASAM3D from HCP105 (same)
./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP105_experiment_MASAM3D_x1 --en Zenedo_to_Zenedo_experiment_MASAM3D_inference_x1 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_wholeHCP105_MASAM3D_x9/best_weights_ep307.npz --seg & 
sleep 20
./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP105_experiment_MASAM3D_x1 --en Zenedo_to_Zenedo_experiment_MASAM3D_inference_x2 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_wholeHCP105_MASAM3D_x10/best_weights_ep21.npz  --seg &
sleep 20
./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP105_experiment_MASAM3D_x1 --en Zenedo_to_Zenedo_experiment_MASAM3D_inference_x3 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_wholeHCP105_MASAM3D_x12/best_weights_ep384.npz --seg &
sleep 20

# # MedNext3D from HCP105 (same)
./ExpRunner --fold 0 --data_path $DATA_PATH --config wholeHCP105_experiment_mednext3D --en Zenedo_to_Zenedo_experiment_mednext3D_inference_x1  --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/wholeHCP105_experiment_mednext3D_x21/best_weights_ep160.npz --seg & 
sleep 20
./ExpRunner --fold 1 --data_path $DATA_PATH --config wholeHCP105_experiment_mednext3D --en Zenedo_to_Zenedo_experiment_mednext3D_inference_x2  --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/wholeHCP105_experiment_mednext3D_x22/best_weights_ep191.npz --seg & 
sleep 20
./ExpRunner --fold 2 --data_path $DATA_PATH --config wholeHCP105_experiment_mednext3D --en Zenedo_to_Zenedo_experiment_mednext3D_inference_x3  --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/wholeHCP105_experiment_mednext3D_x23/best_weights_ep197.npz --seg & 
wait
