name: tractseg-benchmark
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - numpy=1.23
  - scipy=1.10
  - scikit-learn
  - matplotlib
  - pandas
  - pytest
  - requests
  - seaborn
  - tqdm
  - joblib
  - psutil
  - h5py
  - nibabel=5.1
  - monai=1.1
  - einops
  - dipy>=1.5.0
  - fury
  - future
  - six
  - simpleitk
  - xvfbwrapper
  - pip:
      - icecream==2.1.3
      - MedPy==0.4.0
      - ml-collections==0.1.1
      - neptune
      - onnx==1.14.0
      - onnxruntime==1.14.1
      - opencv-python==4.7.0.72
      - pycocotools==2.0.6
      - safetensors==0.3.1
      - tensorboardX==2.6
      - wandb
