#!/bin/bash -l 


source /home/junb/miniconda3/bin/activate
conda activate masam

cd /mnt/scratch/junb/TractSegVis/TractSeg

DATA_PATH="/mnt/scratch/junb/TractSegVis/"

# inference only
# TractSeg2D from CamCan to CamCan

CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 0 --data_path $DATA_PATH --config CamCan_experiment_TractSeg --en CamCan_to_CamCan_experiment_TractSeg_inference_x1 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/CamCan_experiment_TractSeg_x1/best_weights_ep224.npz --seg & # --seg --rt --with_id TRAC-469
sleep 20
CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 1 --data_path $DATA_PATH --config CamCan_experiment_TractSeg --en CamCan_to_CamCan_experiment_TractSeg_inference_x2 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/CamCan_experiment_TractSeg_x4/best_weights_ep45.npz --seg & # --seg --rt --with_id TRAC-469
sleep 20
CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 2 --data_path $DATA_PATH --config CamCan_experiment_TractSeg --en CamCan_to_CamCan_experiment_TractSeg_inference_x3 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/CamCan_experiment_TractSeg_x5/best_weights_ep107.npz --seg & # --seg --rt --with_id TRAC-469
sleep 20

# TractSeg2D from HCP+CamCan+PING to CamCan
CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 0 --data_path $DATA_PATH --config CamCan_experiment_TractSeg --en HCP_CamCan_PING_to_CamCan_experiment_TractSeg_inference_x1 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_TractSeg_x2/best_weights_ep22.npz --seg & # --seg --rt --with_id TRAC-469
wait

CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 1 --data_path $DATA_PATH --config CamCan_experiment_TractSeg --en HCP_CamCan_PING_to_CamCan_experiment_TractSeg_inference_x2 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_TractSeg_x3/best_weights_ep25.npz --seg & # --seg --rt --with_id TRAC-469
sleep 20
CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 2 --data_path $DATA_PATH --config CamCan_experiment_TractSeg --en HCP_CamCan_PING_to_CamCan_experiment_TractSeg_inference_x3 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_TractSeg_x4/best_weights_ep26.npz --seg & # --seg --rt --with_id TRAC-469
sleep 20

# TractSeg2D from HCP all to CamCan
CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 0 --data_path $DATA_PATH --config CamCan_experiment_TractSeg --en HCP_to_CamCan_experiment_TractSeg_inference_x1 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/wholeHCP_experiment_TractSeg_x14/best_weights_ep73.npz --seg & # --seg --rt --with_id TRAC-469
sleep 20

CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 1 --data_path $DATA_PATH --config CamCan_experiment_TractSeg --en HCP_to_CamCan_experiment_TractSeg_inference_x2 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/wholeHCP_experiment_TractSeg_x1/best_weights_ep68.npz --seg & # --seg --rt --with_id TRAC-469
wait

CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 2 --data_path $DATA_PATH --config CamCan_experiment_TractSeg --en HCP_to_CamCan_experiment_TractSe_inference_x3 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/wholeHCP_experiment_TractSeg_x15/best_weights_ep52.npz --seg & # --seg --rt --with_id TRAC-469
sleep 20


# TractSeg2D from HCP+PING to CamCan
CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 0 --data_path $DATA_PATH --config CamCan_experiment_TractSeg --en HCP_PING_to_CamCan_experiment_TractSeg_inference_x1 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_Ping_experiment_TractSeg/best_weights_ep37.npz --seg &
sleep 20
CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 1 --data_path $DATA_PATH --config CamCan_experiment_TractSeg --en HCP_PING_to_CamCan_experiment_TractSeg_inference_x2 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_Ping_experiment_TractSeg_x1/best_weights_ep48.npz --seg &
sleep 20
CUDA_VISIBLE_DEVICES=0 ./ExpRunner --fold 2 --data_path $DATA_PATH --config CamCan_experiment_TractSeg --en HCP_PING_to_CamCan_experiment_TractSeg_inference_x3 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_Ping_experiment_TractSeg_x2/best_weights_ep42.npz --seg &
wait






# inference only
 #--seg 
