#!/bin/bash -l 

source /home/junb/miniconda3/bin/activate
conda activate masam

cd /mnt/scratch/junb/TractSegVis/TractSeg

DATA_PATH="/mnt/scratch/junb/TractSegVis/"

# inference only
# 3D SwinUNETR
# from CamCan
./ExpRunner --fold 0 --data_path $DATA_PATH --config CamCan_experiment_swinunetr3D --en CamCan_to_CamCan_swinunetr3D_x1 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_CamCan_swinunetr3D_x2/best_weights_ep20.npz --seg &
sleep 20    
./ExpRunner --fold 1 --data_path $DATA_PATH --config CamCan_experiment_swinunetr3D --en CamCan_to_CamCan_swinunetr3D_x2 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_CamCan_swinunetr3D_x6/best_weights_ep13.npz --seg &
sleep 20
# we should note that I used the weights were overriden
./ExpRunner --fold 2 --data_path $DATA_PATH --config CamCan_experiment_swinunetr3D --en CamCan_to_CamCan_swinunetr3D_x3 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_CamCan_swinunetr3D_x6/best_weights_ep13.npz --seg &
sleep 20


# from HCP+CamCan+PING
./ExpRunner --fold 0 --data_path $DATA_PATH --config CamCan_experiment_swinunetr3D --en HCP_CamCan_PING_to_CamCan_swinunetr3D_x1 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_swinunetr3D_x2/best_weights_ep7.npz --seg &
wait
./ExpRunner --fold 1 --data_path $DATA_PATH --config CamCan_experiment_swinunetr3D --en HCP_CamCan_PING_to_CamCan_swinunetr3D_x2 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_swinunetr3D_x3/best_weights_ep8.npz --seg &
sleep 20
./ExpRunner --fold 2 --data_path $DATA_PATH --config CamCan_experiment_swinunetr3D --en HCP_CamCan_PING_to_CamCan_swinunetr3D_x3 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_swinunetr3D_x4/best_weights_ep7.npz --seg &
sleep 20

# from HCP all
./ExpRunner --fold 0 --data_path $DATA_PATH --config CamCan_experiment_swinunetr3D --en HCP_to_CamCan_swinunetr3D_x1 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_wholeHCP_swinunetr3D_x12/best_weights_ep26.npz --seg &
sleep 20


./ExpRunner --fold 1 --data_path $DATA_PATH --config CamCan_experiment_swinunetr3D --en HCP_to_CamCan_swinunetr3D_x2 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_wholeHCP_swinunetr3D_x80/best_weights_ep6.npz --seg &
wait

./ExpRunner --fold 2 --data_path $DATA_PATH --config CamCan_experiment_swinunetr3D --en HCP_to_CamCan_swinunetr3D_x3 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/run_with_wholeHCP_swinunetr3D_x81/best_weights_ep6.npz --seg &
sleep 20

# from HCP+PING
./ExpRunner --fold 0 --data_path $DATA_PATH --config CamCan_experiment_swinunetr3D --en HCP_PING_to_CamCan_swinunetr3D_x1 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_Ping_experiment_swinunetr3D/best_weights_ep8.npz --seg &
wait
sleep 20
./ExpRunner --fold 1 --data_path $DATA_PATH --config CamCan_experiment_swinunetr3D --en HCP_PING_to_CamCan_swinunetr3D_x2 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_Ping_experiment_swinunetr3D_x1/best_weights_ep8.npz --seg &
sleep 20
./ExpRunner --fold 2 --data_path $DATA_PATH --config CamCan_experiment_swinunetr3D --en HCP_PING_to_CamCan_swinunetr3D_x3 --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_Ping_experiment_swinunetr3D_x7/best_weights_ep8.npz --seg &
wait


