#!/bin/bash -l 

source /home/junb/miniconda3/bin/activate
conda activate masam

cd /mnt/scratch/junb/TractSegVis/TractSeg

DATA_PATH="/mnt/scratch/junb/TractSegVis/"

# inference only
# 3D mednext3d
./ExpRunner --fold 0 --data_path $DATA_PATH --config CamCan_experiment_mednext3D --en CamCan_to_CamCan_experiment_mednext3D --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/CamCan_experiment_mednext3D/best_weights_ep26.npz --seg & #--rt --with_id TRAC-444
sleep 20

./ExpRunner --fold 1 --data_path $DATA_PATH --config CamCan_experiment_mednext3D --en CamCan_to_CamCan_experiment_mednext3D --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/CamCan_experiment_mednext3D_x5/best_weights_ep26.npz --seg & #--rt --with_id TRAC-444
sleep 20

./ExpRunner --fold 2 --data_path $DATA_PATH --config CamCan_experiment_mednext3D --en CamCan_to_CamCan_experiment_mednext3D --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/CamCan_experiment_mednext3D_x4/best_weights_ep30.npz --seg & #--rt --with_id TRAC-444
sleep 20

# from HCP+CAMCAN+PING
./ExpRunner --fold 0 --data_path $DATA_PATH --config CamCan_experiment_mednext3D --en HCP_CamCan_PING_to_CamCan_experiment_mednext3D --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_mednext3D/best_weights_ep18.npz --seg & # --seg --rt --with_id TRAC-469
wait
./ExpRunner --fold 1 --data_path $DATA_PATH --config CamCan_experiment_mednext3D --en HCP_CamCan_PING_to_CamCan_experiment_mednext3D --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_mednext3D_x1/best_weights_ep16.npz --seg & # --seg --rt --with_id TRAC-469
sleep 20
./ExpRunner --fold 2 --data_path $DATA_PATH --config CamCan_experiment_mednext3D --en HCP_CamCan_PING_to_CamCan_experiment_mednext3D --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_CamCan_Ping_experiment_mednext3D_x2/best_weights_ep14.npz --seg & # --seg --rt --with_id TRAC-469
sleep 20

# from HCP all
./ExpRunner --fold 0 --data_path $DATA_PATH --config CamCan_experiment_mednext3D --en HCP_to_CamCan_experiment_mednext3D --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/wholeHCP105_experiment_mednext3D_x20/best_weights_ep76.npz --seg & # --seg --rt --with_id TRAC-469
sleep 20

./ExpRunner --fold 1 --data_path $DATA_PATH --config CamCan_experiment_mednext3D --en HCP_to_CamCan_experiment_mednext3D --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/wholeHCP105_experiment_mednext3D_x21/best_weights_ep160.npz  --seg & # --seg --rt --with_id TRAC-469
wait
./ExpRunner --fold 2 --data_path $DATA_PATH --config CamCan_experiment_mednext3D --en HCP_to_CamCan_experiment_mednext3D --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/wholeHCP105_experiment_mednext3D_x22/best_weights_ep191.npz  --seg & # --seg --rt --with_id TRAC-469
sleep 20



# MedNext3D from HCP+PING
./ExpRunner --fold 0 --data_path $DATA_PATH --config CamCan_experiment_mednext3D --en HCP_PING_to_CamCan_experiment_mednext3D --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_Ping_experiment_mednext3D/best_weights_ep21.npz --seg &
sleep 20

./ExpRunner --fold 1 --data_path $DATA_PATH --config CamCan_experiment_mednext3D --en HCP_PING_to_CamCan_experiment_mednext3D --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_Ping_experiment_mednext3D_x1/best_weights_ep21.npz --seg &
sleep 20

./ExpRunner --fold 2 --data_path $DATA_PATH --config CamCan_experiment_mednext3D --en HCP_PING_to_CamCan_experiment_mednext3D --train False --test True --lw --weights_path /mnt/storage/junb/hcp_ecp/HCP_Ping_experiment_mednext3D_x2/best_weights_ep20.npz --seg &
wait